name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php: ['7.4', '8.0', '8.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer Validate
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 11 -s composer -e 'validate'

      - name: Composer Install
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 11 -s composerInstall

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 11 -s lint

      - name: Validate code against CGL
        run: PHP_CS_FIXER_IGNORE_ENV=1 Build/Scripts/runTests.sh -p 8.1 -t 11 -s cgl -n

      - name: Unit tests
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 11 -s unit
