name: TYPO3 13

on: [pull_request]

jobs:
  lint:
    name: Linting
    runs-on: self-hosted
    strategy:
      fail-fast: true
      matrix:
        php:
          - '8.2'
          - '8.3'

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Lint PHP'
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint
