name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php: ['8.1', '8.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer Install
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 12 -s composerUpdate

      - name: Composer validate
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s composer -e 'validate'

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

      - name: Unit tests
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit
