name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php: ['7.4', '8.0', '8.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer Install
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 11 -s composerUpdate

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s lint

      - name: Unit tests
        run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -s unit
